---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.1
env:
  global:
    # encrypted GITHUB_API_TOKEN for librarian-puppet
    secure: "iDN5Q63C84XHRtLWk58pqR8PPBbC+xa0D33U6SyyrCoiQPh/uEJg0nW3gQ6akkOgs+H2ULj9kIjI+Qb/WEIAlDmA+tCiGDWXfBVtfvPNpENem14ovUkfE2HaRWE40d+cYFT6CmjrRA8t3yD2kGHRFeMh3gwlfdCtyf8TydDNG7I="
